CREATE DATABASE IF NOT EXISTS albaraka;
USE albaraka;

CREATE TABLE Client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Compte (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(50) NOT NULL UNIQUE,
    solde DECIMAL(15, 2) NOT NULL DEFAULT 0.0,
    idClient INT NOT NULL,
    typeCompte ENUM('COURANT', 'EPARGNE') NOT NULL,
    decouvertAutorise DECIMAL(15, 2) DEFAULT NULL,
    tauxInteret DECIMAL(5, 2) DEFAULT NULL,
    FOREIGN KEY (idClient) REFERENCES Client(id) ON DELETE CASCADE
);

CREATE TABLE Transaction (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATETIME NOT NULL,
    montant DECIMAL(15, 2) NOT NULL,
    type ENUM('VERSEMENT', 'RETRAIT', 'VIREMENT') NOT NULL,
    lieu VARCHAR(100) NOT NULL,
    idCompte INT NOT NULL,
    FOREIGN KEY (idCompte) REFERENCES Compte(id) ON DELETE CASCADE
);
